create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create table if not exists public.roster_members (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 100),
  attacked boolean not null default false,
  position integer not null
);

alter table public.admins enable row level security;
alter table public.roster_members enable row level security;

create policy "Admins can read their own access record"
on public.admins for select
to authenticated
using (user_id = auth.uid());

create policy "Roster is publicly readable"
on public.roster_members for select
to anon, authenticated
using (true);

create policy "Admins can update roster"
on public.roster_members for update
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()))
with check (exists (select 1 from public.admins where user_id = auth.uid()));

create or replace function public.replace_roster(new_members jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from public.admins where user_id = auth.uid()) then
    raise exception 'Administrator access required';
  end if;

  delete from public.roster_members;
  insert into public.roster_members (name, attacked, position)
  select
    left(trim(member->>'name'), 100),
    coalesce((member->>'attacked')::boolean, false),
    ordinality - 1
  from jsonb_array_elements(new_members) with ordinality as entries(member, ordinality)
  where trim(member->>'name') <> '';
end;
$$;

revoke all on function public.replace_roster(jsonb) from public, anon;
grant execute on function public.replace_roster(jsonb) to authenticated;

alter publication supabase_realtime add table public.roster_members;

-- After creating the admin in Authentication > Users, replace the email below
-- and run this statement once in the Supabase SQL editor:
-- insert into public.admins (user_id)
-- select id from auth.users where email = 'admin@example.com';